diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["left_wheel"]
    right_wheel_names: ["right_wheel"]
    wheel_separation: 0.4
    wheels_per_side: 1
    wheel_radius: 0.1
    publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: base_link
    open_loop: true
    enable_odom_tf: true
    cmd_vel_timeout: 0.5
    use_stamped_vel: false
